/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado del servicio
         * @description Devuelve un texto fijo que confirma que el backend está en pie. No consulta la base de datos ni requiere autenticación.
         */
        get: operations["AppController_estado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar disponibilidad
         * @description Indica si hay lugar para una cantidad de comensales en una fecha, un turno y una zona. Consulta una sola combinación y es una foto del momento: no reserva ni bloquea nada, y la validación real ocurre al crear la reserva. Evalúa siempre todas las reglas y devuelve todas las que fallan. Que no haya lugar no es un error: la respuesta es `200` con `disponible` en `false`. Es una ruta pública, sin autenticación.
         */
        get: operations["DisponibilidadController_consultar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login de administrador
         * @description Autentica a un usuario administrador con email y contraseña, y devuelve un JWT de acceso (openspec/config.yaml §5).
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/zonas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado de Zonas
         * @description Lista las Zonas del salón — spec: "Alta y baja de Zona no soportadas", solo hay lectura y actualización de configuración.
         */
        get: operations["ZonasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/zonas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar configuración de una Zona
         * @description Rechaza con 400 si, combinando los campos del body con los ya persistidos, el mínimo de comensales resultante queda por encima del máximo.
         */
        patch: operations["ZonasController_actualizar"];
        trace?: never;
    };
    "/admin/mesas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado de Mesas
         * @description Sin `zonaId` devuelve todas las Mesas de todas las Zonas.
         */
        get: operations["MesasController_listar"];
        put?: never;
        /**
         * Alta de Mesa
         * @description Rechaza con 404 si la Zona indicada no existe, con 409 si ya existe una mesa con esa etiqueta.
         */
        post: operations["MesasController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mesas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Baja de Mesa
         * @description Elimina físicamente la Mesa solo si no tiene ninguna Reserva asociada, de ningún estado — spec: "Baja de Mesa preserva las Reservas activas e históricas".
         */
        delete: operations["MesasController_eliminar"];
        options?: never;
        head?: never;
        /**
         * Edición de Mesa
         * @description Rechaza con 409 si el cambio dejaría inválida una Reserva activa existente (capacidad insuficiente o Zona distinta) — spec: "Edición de Mesa preserva las Reservas activas".
         */
        patch: operations["MesasController_actualizar"];
        trace?: never;
    };
    "/admin/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado de Turnos
         * @description Incluye los Turnos inactivos.
         */
        get: operations["HorariosController_listar"];
        put?: never;
        /**
         * Alta de Turno
         * @description Si el body no especifica `activo`, el Turno queda `activo: true` por defecto.
         */
        post: operations["HorariosController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/turnos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edición y activación/desactivación de Turno
         * @description `activo` viaja en el mismo PATCH de edición que día/horario, sin una ruta aparte de activar/desactivar.
         */
        patch: operations["HorariosController_actualizar"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description Email del usuario administrador.
             * @example admin@restaurante-mvp.local
             */
            email: string;
            /**
             * @description Contraseña del usuario administrador.
             * @example AdminMVP2026!
             */
            password: string;
        };
        LoginResponseDto: {
            /**
             * @description JWT de acceso del administrador (ver openspec/config.yaml §5).
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIn0.abc123
             */
            accessToken: string;
        };
        ZonaRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /**
             * @example VIP
             * @enum {string}
             */
            nombre: "STANDARD" | "VIP";
            /** @example 2 */
            minComensales: number;
            /** @example 12 */
            maxComensales: number;
            /** @example 24 */
            anticipacionMinHoras: number;
            /** @example 60 */
            anticipacionMaxDias: number;
            /** @example 24 */
            ventanaCancelacionHoras: number;
            /** @example true */
            requiereConfirmacionAdmin: boolean;
            /** @example 20 */
            aforoMaximo: number;
        };
        ActualizarZonaDto: {
            /**
             * @description Mínimo de comensales permitido en una Reserva de esta Zona.
             * @example 2
             */
            minComensales?: number;
            /**
             * @description Máximo de comensales permitido en una Reserva de esta Zona.
             * @example 12
             */
            maxComensales?: number;
            /**
             * @description Anticipación mínima, en horas, para reservar en esta Zona.
             * @example 24
             */
            anticipacionMinHoras?: number;
            /**
             * @description Anticipación máxima, en días, para reservar en esta Zona.
             * @example 60
             */
            anticipacionMaxDias?: number;
            /**
             * @description Ventana de cancelación, en horas, antes del turno reservado.
             * @example 24
             */
            ventanaCancelacionHoras?: number;
            /**
             * @description Si una Reserva en esta Zona requiere confirmación manual del admin.
             * @example true
             */
            requiereConfirmacionAdmin?: boolean;
            /**
             * @description Aforo máximo simultáneo de esta Zona.
             * @example 20
             */
            aforoMaximo?: number;
        };
        CrearMesaDto: {
            /**
             * @description Id de la Zona a la que pertenece la Mesa.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            zonaId: string;
            /**
             * @description Capacidad de comensales de la Mesa.
             * @example 4
             */
            capacidad: number;
            /**
             * @description Etiqueta identificatoria de la Mesa, única en todo el salón.
             * @example M1
             */
            etiqueta: string;
        };
        MesaRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            zonaId: string;
            /** @example 4 */
            capacidad: number;
            /** @example M1 */
            etiqueta: string;
        };
        ActualizarMesaDto: {
            /**
             * @description Id de la nueva Zona a la que pasa a pertenecer la Mesa.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            zonaId?: string;
            /**
             * @description Nueva capacidad de comensales de la Mesa.
             * @example 6
             */
            capacidad?: number;
            /**
             * @description Nueva etiqueta identificatoria de la Mesa, única en todo el salón.
             * @example M1
             */
            etiqueta?: string;
        };
        CrearTurnoDto: {
            /**
             * @description Día de la semana en que rige este Turno.
             * @example VIERNES
             * @enum {string}
             */
            diaSemana: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            /**
             * @description Hora local del restaurante en que empieza el Turno, formato `HH:mm` o `HH:mm:ss`.
             * @example 20:00
             */
            horaInicio: string;
            /**
             * @description Hora local del restaurante en que termina el Turno, formato `HH:mm` o `HH:mm:ss`. Puede ser menor a `horaInicio`: se interpreta como cruce de medianoche.
             * @example 23:30
             */
            horaFin: string;
            /**
             * @description Si el Turno queda activo al crearse.
             * @default true
             * @example true
             */
            activo: boolean;
        };
        TurnoRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /**
             * @example VIERNES
             * @enum {string}
             */
            diaSemana: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            /** @example 1970-01-01T20:00:00.000Z */
            horaInicio: string;
            /** @example 1970-01-01T23:30:00.000Z */
            horaFin: string;
            /** @example true */
            activo: boolean;
        };
        ActualizarTurnoDto: {
            /**
             * @description Nuevo día de la semana en que rige este Turno.
             * @example VIERNES
             * @enum {string}
             */
            diaSemana?: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            /**
             * @description Nueva hora local de inicio del Turno, formato `HH:mm` o `HH:mm:ss`.
             * @example 20:00
             */
            horaInicio?: string;
            /**
             * @description Nueva hora local de fin del Turno, formato `HH:mm` o `HH:mm:ss`. Puede ser menor a `horaInicio`: se interpreta como cruce de medianoche.
             * @example 23:30
             */
            horaFin?: string;
            /**
             * @description Activa o desactiva el Turno sin eliminarlo.
             * @example false
             */
            activo?: boolean;
        };
        /** @description Resultado de consultar la disponibilidad de una fecha, un turno y una zona. */
        DisponibilidadRespuesta: {
            /**
             * @description `true` si y solo si `motivos` está vacío.
             * @example false
             */
            disponible: boolean;
            /**
             * @description Comensales (no mesas) que todavía entran en ese turno y esa fecha: el mínimo entre lo que queda del aforo de la zona y lo que queda del aforo global, sin descontar los comensales pedidos. Nunca es negativo.
             * @example 20
             */
            lugaresRestantes: number;
            /** @description Todas las reglas que impiden la reserva, en el orden fijo de `CodigoMotivo`. Vacío si hay lugar. */
            motivos: components["schemas"]["MotivoNoDisponible"][];
        };
        /** @description Una regla de negocio que impide la reserva pedida. */
        MotivoNoDisponible: {
            /** @description Código estable de la regla que falla. El frontend arma el texto para el usuario a partir de este código. Los valores se evalúan y se listan en este orden: `TURNO_INACTIVO` (el turno está inactivo), `TURNO_NO_CORRESPONDE_A_FECHA` (el día de la semana de la fecha no es el del turno), `ANTICIPACION_MINIMA` (falta menos que la anticipación mínima de la zona, o el turno ya pasó), `ANTICIPACION_MAXIMA` (falta más que la anticipación máxima de la zona), `COMENSALES_FUERA_DE_RANGO` (fuera del mínimo o máximo de comensales de la zona), `AFORO_ZONA` (se supera el aforo de la zona), `AFORO_GLOBAL` (se supera el aforo global) y `SIN_MESA_DISPONIBLE` (no queda una mesa libre de la zona con capacidad suficiente). */
            codigo: components["schemas"]["CodigoMotivo"];
            /**
             * @description Explicación en español para humanos. No se usa para lógica.
             * @example La zona VIP admite de 2 a 12 comensales por reserva.
             */
            mensaje: string;
        };
        /**
         * @description Código estable de la regla que falla. El frontend arma el texto para el usuario a partir de este código. Los valores se evalúan y se listan en este orden: `TURNO_INACTIVO` (el turno está inactivo), `TURNO_NO_CORRESPONDE_A_FECHA` (el día de la semana de la fecha no es el del turno), `ANTICIPACION_MINIMA` (falta menos que la anticipación mínima de la zona, o el turno ya pasó), `ANTICIPACION_MAXIMA` (falta más que la anticipación máxima de la zona), `COMENSALES_FUERA_DE_RANGO` (fuera del mínimo o máximo de comensales de la zona), `AFORO_ZONA` (se supera el aforo de la zona), `AFORO_GLOBAL` (se supera el aforo global) y `SIN_MESA_DISPONIBLE` (no queda una mesa libre de la zona con capacidad suficiente).
         * @enum {string}
         */
        CodigoMotivo: "TURNO_INACTIVO" | "TURNO_NO_CORRESPONDE_A_FECHA" | "ANTICIPACION_MINIMA" | "ANTICIPACION_MAXIMA" | "COMENSALES_FUERA_DE_RANGO" | "AFORO_ZONA" | "AFORO_GLOBAL" | "SIN_MESA_DISPONIBLE";
        /** @description Cuerpo de error por defecto de NestJS. En un `400` del `ValidationPipe`, `message` es la lista de problemas encontrados; en un `404`, es un único texto. */
        ErrorRespuesta: {
            /**
             * @description Código HTTP de la respuesta.
             * @example 404
             */
            statusCode: number;
            /** @description Detalle del error. Un texto, o una lista de textos si son varios. */
            message: string | string[];
            /**
             * @description Nombre estándar del código HTTP.
             * @example Not Found
             */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_estado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El backend está operativo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    DisponibilidadController_consultar: {
        parameters: {
            query: {
                /** @description Fecha de calendario local del restaurante, sin hora (`YYYY-MM-DD`). Un instante con hora (por ejemplo `2026-09-15T12:00:00Z`) o una fecha inexistente se rechazan con `400`. */
                fecha: string;
                /** @description Id del turno a consultar. */
                turnoId: string;
                /** @description Id de la zona a consultar. */
                zonaId: string;
                /** @description Cantidad de comensales de la reserva que se quiere hacer. Entero, mínimo 1. */
                comensales: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La consulta es válida. Informa si hay lugar, cuántos comensales entran todavía y, si no hay lugar, todos los motivos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadRespuesta"];
                };
            };
            /** @description La consulta está mal formada: falta un parámetro, la fecha no es `YYYY-MM-DD` o no existe, un id no es UUID, o `comensales` no es un entero mayor o igual a 1. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description El turno o la zona indicados no existen. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login exitoso: devuelve el JWT de acceso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Credenciales inválidas: email inexistente o contraseña incorrecta. El mensaje es genérico y no distingue cuál dato falló. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Se superó el límite de intentos de login permitidos en la ventana configurada (rate limiting). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ZonasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Zonas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonaRespuestaDto"][];
                };
            };
        };
    };
    ZonasController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarZonaDto"];
            };
        };
        responses: {
            /** @description La zona se actualizó. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonaRespuestaDto"];
                };
            };
            /** @description La zona indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No se pudo actualizar la zona por una edición concurrente (conflicto de serialización agotando los reintentos). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MesasController_listar: {
        parameters: {
            query?: {
                /** @description Filtra las Mesas devueltas por Zona. */
                zonaId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Mesas, opcionalmente filtrado por Zona. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MesaRespuestaDto"][];
                };
            };
        };
    };
    MesasController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearMesaDto"];
            };
        };
        responses: {
            /** @description La mesa se creó. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MesaRespuestaDto"];
                };
            };
            /** @description La zona indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe una mesa con esa etiqueta. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MesasController_eliminar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La mesa se eliminó, sin cuerpo en la respuesta. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La mesa indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La mesa tiene reservas asociadas de cualquier estado (PENDIENTE, CONFIRMADA, CANCELADA o NO_SHOW): no se puede eliminar. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MesasController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarMesaDto"];
            };
        };
        responses: {
            /** @description La mesa se actualizó. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MesaRespuestaDto"];
                };
            };
            /** @description La mesa o la zona indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La mesa tiene una reserva activa con más comensales que la nueva capacidad, reservas activas que impiden cambiarla de zona, ya existe otra mesa con la etiqueta indicada, o no se pudo actualizar por una edición concurrente (conflicto de serialización agotando los reintentos). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HorariosController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Turnos, incluidos los inactivos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoRespuestaDto"][];
                };
            };
        };
    };
    HorariosController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearTurnoDto"];
            };
        };
        responses: {
            /** @description El turno se creó. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoRespuestaDto"];
                };
            };
            /** @description Ya existe un turno para ese día y esa hora de inicio. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HorariosController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarTurnoDto"];
            };
        };
        responses: {
            /** @description El turno se actualizó. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoRespuestaDto"];
                };
            };
            /** @description El turno indicado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe un turno para ese día y esa hora de inicio. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
