/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado del servicio
         * @description Devuelve un texto fijo que confirma que el backend está en pie. No consulta la base de datos ni requiere autenticación.
         */
        get: operations["AppController_estado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar disponibilidad
         * @description Indica si hay lugar para una cantidad de comensales en una fecha, un turno y una zona. Consulta una sola combinación y es una foto del momento: no reserva ni bloquea nada, y la validación real ocurre al crear la reserva. Evalúa siempre todas las reglas y devuelve todas las que fallan. Que no haya lugar no es un error: la respuesta es `200` con `disponible` en `false`. Es una ruta pública, sin autenticación.
         */
        get: operations["DisponibilidadController_consultar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zonas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo público de Zonas
         * @description Lista todas las Zonas con los campos no sensibles que necesita el formulario de reserva del cliente, ordenadas por nombre (`STANDARD` antes que `VIP`). No incluye `aforoMaximo` ni las Mesas de la zona. Es una ruta pública, sin autenticación.
         */
        get: operations["ZonasPublicasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo público de Turnos activos
         * @description Lista los Turnos con `activo: true`, ordenados por día de la semana (lunes a domingo) y, dentro del mismo día, por hora de inicio. Es una ruta pública, sin autenticación.
         */
        get: operations["TurnosPublicosController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear una reserva
         * @description Crea una reserva sin cuenta para una fecha, un turno, una zona y una cantidad de comensales. Evalúa las mismas reglas que la consulta de disponibilidad en el momento de crear, asigna automáticamente la mesa libre más chica que alcance y genera el código de reserva. Queda `PENDIENTE` si la zona requiere confirmación del admin y `CONFIRMADA` si no. El cliente no elige mesa, estado ni código: si los manda, se responde 400. Es una ruta pública, sin autenticación.
         */
        post: operations["ReservasController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/consultar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar una reserva por código y email
         * @description Devuelve el estado de una reserva sin cuenta. Exige el código y el email de la misma reserva; el código y el email se comparan sin distinguir mayúsculas y minúsculas. Si el código no existe o el email no coincide, responde el mismo `404`, para que no se pueda averiguar si un código existe. Devuelve solo una vista mínima: no incluye la mesa ni los datos de contacto. Es una ruta pública, sin autenticación, con límite de solicitudes por cliente.
         */
        post: operations["ReservasController_consultar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{codigo}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancelar una reserva por código y email
         * @description Cancela una reserva PENDIENTE o CONFIRMADA dentro de la ventana mínima de cancelación de su zona (2 h STANDARD / 24 h VIP). El límite exacto de la ventana está permitido. Exige el código y el email de la misma reserva; si no coinciden, responde el mismo 404 que la consulta, sin indicar cuál dato era incorrecto. Es una ruta pública, sin autenticación, con límite de solicitudes por cliente.
         */
        post: operations["ReservasController_cancelar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login de administrador
         * @description Autentica a un usuario administrador con email y contraseña, y devuelve un JWT de acceso (openspec/config.yaml §5).
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/zonas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado de Zonas
         * @description Lista las Zonas del salón — spec: "Alta y baja de Zona no soportadas", solo hay lectura y actualización de configuración.
         */
        get: operations["ZonasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/zonas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar configuración de una Zona
         * @description Rechaza con 400 si, combinando los campos del body con los ya persistidos, el mínimo de comensales resultante queda por encima del máximo.
         */
        patch: operations["ZonasController_actualizar"];
        trace?: never;
    };
    "/admin/mesas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado de Mesas
         * @description Sin `zonaId` devuelve todas las Mesas de todas las Zonas.
         */
        get: operations["MesasController_listar"];
        put?: never;
        /**
         * Alta de Mesa
         * @description Rechaza con 404 si la Zona indicada no existe, con 409 si ya existe una mesa con esa etiqueta.
         */
        post: operations["MesasController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/mesas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Baja de Mesa
         * @description Elimina físicamente la Mesa solo si no tiene ninguna Reserva asociada, de ningún estado — spec: "Baja de Mesa preserva las Reservas activas e históricas".
         */
        delete: operations["MesasController_eliminar"];
        options?: never;
        head?: never;
        /**
         * Edición de Mesa
         * @description Rechaza con 409 si el cambio dejaría inválida una Reserva activa existente (capacidad insuficiente o Zona distinta) — spec: "Edición de Mesa preserva las Reservas activas".
         */
        patch: operations["MesasController_actualizar"];
        trace?: never;
    };
    "/admin/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado de Turnos
         * @description Incluye los Turnos inactivos.
         */
        get: operations["HorariosController_listar"];
        put?: never;
        /**
         * Alta de Turno
         * @description Si el body no especifica `activo`, el Turno queda `activo: true` por defecto.
         */
        post: operations["HorariosController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/turnos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edición y activación/desactivación de Turno
         * @description `activo` viaja en el mismo PATCH de edición que día/horario, sin una ruta aparte de activar/desactivar.
         */
        patch: operations["HorariosController_actualizar"];
        trace?: never;
    };
    "/admin/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reservas
         * @description Lista las reservas con sus datos de contacto, la mesa y el identificador que usan las demás rutas de admin. Se puede filtrar por fecha, estado, zona y turno; los filtros se combinan todos juntos. El orden es cronológico (fecha, hora de inicio del turno, fecha de creación, identificador) y está paginado. Un filtro con un identificador inexistente devuelve una lista vacía. Requiere un JWT de rol `ADMIN` y tiene un límite de solicitudes por cliente.
         */
        get: operations["ReservasController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reservas/{id}/no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Marcar una reserva como ausente (NO_SHOW)
         * @description Transiciona una reserva CONFIRMADA a NO_SHOW. Rechaza con 409 si la reserva no está CONFIRMADA o si su turno todavía no terminó (el instante exacto de fin también se rechaza). Requiere un JWT de rol ADMIN.
         */
        patch: operations["ReservasController_marcarNoShow"];
        trace?: never;
    };
    "/admin/reservas/{id}/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Confirmar una reserva pendiente
         * @description Transiciona una reserva PENDIENTE a CONFIRMADA. Rechaza con 409 si la reserva no está PENDIENTE. No revalida aforo ni disponibilidad de mesa. Requiere un JWT de rol ADMIN.
         */
        patch: operations["ReservasController_confirmar"];
        trace?: never;
    };
    "/admin/reservas/{id}/rechazar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rechazar una reserva pendiente
         * @description Transiciona una reserva PENDIENTE a CANCELADA. Rechaza con 409 si la reserva no está PENDIENTE (a diferencia de la cancelación del cliente, no acepta reservas CONFIRMADA). Requiere un JWT de rol ADMIN.
         */
        patch: operations["ReservasController_rechazar"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description Email del usuario administrador.
             * @example admin@restaurante-mvp.local
             */
            email: string;
            /**
             * @description Contraseña del usuario administrador.
             * @example AdminMVP2026!
             */
            password: string;
        };
        LoginResponseDto: {
            /**
             * @description JWT de acceso del administrador (ver openspec/config.yaml §5).
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIn0.abc123
             */
            accessToken: string;
        };
        ZonaRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /**
             * @example VIP
             * @enum {string}
             */
            nombre: "STANDARD" | "VIP";
            /** @example 2 */
            minComensales: number;
            /** @example 12 */
            maxComensales: number;
            /** @example 24 */
            anticipacionMinHoras: number;
            /** @example 60 */
            anticipacionMaxDias: number;
            /** @example 24 */
            ventanaCancelacionHoras: number;
            /** @example true */
            requiereConfirmacionAdmin: boolean;
            /** @example 20 */
            aforoMaximo: number;
        };
        ActualizarZonaDto: {
            /**
             * @description Mínimo de comensales permitido en una Reserva de esta Zona.
             * @example 2
             */
            minComensales?: number;
            /**
             * @description Máximo de comensales permitido en una Reserva de esta Zona.
             * @example 12
             */
            maxComensales?: number;
            /**
             * @description Anticipación mínima, en horas, para reservar en esta Zona.
             * @example 24
             */
            anticipacionMinHoras?: number;
            /**
             * @description Anticipación máxima, en días, para reservar en esta Zona.
             * @example 60
             */
            anticipacionMaxDias?: number;
            /**
             * @description Ventana de cancelación, en horas, antes del turno reservado.
             * @example 24
             */
            ventanaCancelacionHoras?: number;
            /**
             * @description Si una Reserva en esta Zona requiere confirmación manual del admin.
             * @example true
             */
            requiereConfirmacionAdmin?: boolean;
            /**
             * @description Aforo máximo simultáneo de esta Zona.
             * @example 20
             */
            aforoMaximo?: number;
        };
        CrearMesaDto: {
            /**
             * @description Id de la Zona a la que pertenece la Mesa.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            zonaId: string;
            /**
             * @description Capacidad de comensales de la Mesa.
             * @example 4
             */
            capacidad: number;
            /**
             * @description Etiqueta identificatoria de la Mesa, única en todo el salón.
             * @example M1
             */
            etiqueta: string;
        };
        MesaRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            zonaId: string;
            /** @example 4 */
            capacidad: number;
            /** @example M1 */
            etiqueta: string;
        };
        ActualizarMesaDto: {
            /**
             * @description Id de la nueva Zona a la que pasa a pertenecer la Mesa.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            zonaId?: string;
            /**
             * @description Nueva capacidad de comensales de la Mesa.
             * @example 6
             */
            capacidad?: number;
            /**
             * @description Nueva etiqueta identificatoria de la Mesa, única en todo el salón.
             * @example M1
             */
            etiqueta?: string;
        };
        CrearTurnoDto: {
            /**
             * @description Día de la semana en que rige este Turno.
             * @example VIERNES
             * @enum {string}
             */
            diaSemana: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            /**
             * @description Hora local del restaurante en que empieza el Turno, formato `HH:mm` o `HH:mm:ss`.
             * @example 20:00
             */
            horaInicio: string;
            /**
             * @description Hora local del restaurante en que termina el Turno, formato `HH:mm` o `HH:mm:ss`. Puede ser menor a `horaInicio`: se interpreta como cruce de medianoche.
             * @example 23:30
             */
            horaFin: string;
            /**
             * @description Si el Turno queda activo al crearse.
             * @default true
             * @example true
             */
            activo: boolean;
        };
        TurnoRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /**
             * @example VIERNES
             * @enum {string}
             */
            diaSemana: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            /** @example 1970-01-01T20:00:00.000Z */
            horaInicio: string;
            /** @example 1970-01-01T23:30:00.000Z */
            horaFin: string;
            /** @example true */
            activo: boolean;
        };
        ActualizarTurnoDto: {
            /**
             * @description Nuevo día de la semana en que rige este Turno.
             * @example VIERNES
             * @enum {string}
             */
            diaSemana?: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            /**
             * @description Nueva hora local de inicio del Turno, formato `HH:mm` o `HH:mm:ss`.
             * @example 20:00
             */
            horaInicio?: string;
            /**
             * @description Nueva hora local de fin del Turno, formato `HH:mm` o `HH:mm:ss`. Puede ser menor a `horaInicio`: se interpreta como cruce de medianoche.
             * @example 23:30
             */
            horaFin?: string;
            /**
             * @description Activa o desactiva el Turno sin eliminarlo.
             * @example false
             */
            activo?: boolean;
        };
        /** @description Resultado de consultar la disponibilidad de una fecha, un turno y una zona. */
        DisponibilidadRespuesta: {
            /**
             * @description `true` si y solo si `motivos` está vacío.
             * @example false
             */
            disponible: boolean;
            /**
             * @description Comensales (no mesas) que todavía entran en ese turno y esa fecha: el mínimo entre lo que queda del aforo de la zona y lo que queda del aforo global, sin descontar los comensales pedidos. Nunca es negativo.
             * @example 20
             */
            lugaresRestantes: number;
            /** @description Todas las reglas que impiden la reserva, en el orden fijo de `CodigoMotivo`. Vacío si hay lugar. */
            motivos: components["schemas"]["MotivoNoDisponible"][];
        };
        /** @description Una regla de negocio que impide la reserva pedida. */
        MotivoNoDisponible: {
            /** @description Código estable de la regla que falla. El frontend arma el texto para el usuario a partir de este código. Los valores se evalúan y se listan en este orden: `TURNO_INACTIVO` (el turno está inactivo), `TURNO_NO_CORRESPONDE_A_FECHA` (el día de la semana de la fecha no es el del turno), `ANTICIPACION_MINIMA` (falta menos que la anticipación mínima de la zona, o el turno ya pasó), `ANTICIPACION_MAXIMA` (falta más que la anticipación máxima de la zona), `COMENSALES_FUERA_DE_RANGO` (fuera del mínimo o máximo de comensales de la zona), `AFORO_ZONA` (se supera el aforo de la zona), `AFORO_GLOBAL` (se supera el aforo global) y `SIN_MESA_DISPONIBLE` (no queda una mesa libre de la zona con capacidad suficiente). */
            codigo: components["schemas"]["CodigoMotivo"];
            /**
             * @description Explicación en español para humanos. No se usa para lógica.
             * @example La zona VIP admite de 2 a 12 comensales por reserva.
             */
            mensaje: string;
        };
        /**
         * @description Código estable de la regla que falla. El frontend arma el texto para el usuario a partir de este código. Los valores se evalúan y se listan en este orden: `TURNO_INACTIVO` (el turno está inactivo), `TURNO_NO_CORRESPONDE_A_FECHA` (el día de la semana de la fecha no es el del turno), `ANTICIPACION_MINIMA` (falta menos que la anticipación mínima de la zona, o el turno ya pasó), `ANTICIPACION_MAXIMA` (falta más que la anticipación máxima de la zona), `COMENSALES_FUERA_DE_RANGO` (fuera del mínimo o máximo de comensales de la zona), `AFORO_ZONA` (se supera el aforo de la zona), `AFORO_GLOBAL` (se supera el aforo global) y `SIN_MESA_DISPONIBLE` (no queda una mesa libre de la zona con capacidad suficiente).
         * @enum {string}
         */
        CodigoMotivo: "TURNO_INACTIVO" | "TURNO_NO_CORRESPONDE_A_FECHA" | "ANTICIPACION_MINIMA" | "ANTICIPACION_MAXIMA" | "COMENSALES_FUERA_DE_RANGO" | "AFORO_ZONA" | "AFORO_GLOBAL" | "SIN_MESA_DISPONIBLE";
        /** @description Cuerpo de error por defecto de NestJS. En un `400` del `ValidationPipe`, `message` es la lista de problemas encontrados; en un `404`, es un único texto. */
        ErrorRespuesta: {
            /**
             * @description Código HTTP de la respuesta.
             * @example 404
             */
            statusCode: number;
            /** @description Detalle del error. Un texto, o una lista de textos si son varios. */
            message: string | string[];
            /**
             * @description Nombre estándar del código HTTP.
             * @example Not Found
             */
            error: string;
        };
        /** @description Datos para crear una reserva sin cuenta. */
        CrearReservaDto: {
            /**
             * Format: date
             * @description Fecha de calendario local del restaurante, sin hora (`YYYY-MM-DD`).
             * @example 2026-09-19
             */
            fecha: string;
            /**
             * Format: uuid
             * @description Id del turno.
             * @example 3f1c2a9e-5b7d-4e8a-9c21-6d4b0f8e1a73
             */
            turnoId: string;
            /**
             * Format: uuid
             * @description Id de la zona.
             * @example b8e4d7c2-1a6f-4c3b-8e95-2f7a0d6c4b19
             */
            zonaId: string;
            /**
             * @description Cantidad de comensales. Entero, mínimo 1.
             * @example 4
             */
            comensales: number;
            /**
             * @description Nombre de quien reserva.
             * @example Ana Pérez
             */
            nombreCliente: string;
            /**
             * Format: email
             * @description Email de quien reserva. Junto con el código, sirve para consultar o cancelar.
             * @example ana.perez@example.com
             */
            emailCliente: string;
            /**
             * @description Teléfono de contacto, en formato libre.
             * @example +54 9 11 5555-1234
             */
            telefonoCliente: string;
        };
        /** @description Reserva recién creada, sin datos internos ni de contacto. */
        ReservaCreadaRespuesta: {
            /**
             * @description Código alfanumérico de 8 caracteres, único. Junto con el email, identifica la reserva.
             * @example K7PM3QXA
             */
            codigoReserva: string;
            /**
             * @description `PENDIENTE` si la zona requiere confirmación del admin, `CONFIRMADA` si no. Una reserva recién creada nunca está `CANCELADA` ni `NO_SHOW`.
             * @example CONFIRMADA
             * @enum {string}
             */
            estado: "PENDIENTE" | "CONFIRMADA";
            /**
             * Format: date
             * @description La misma fecha de calendario local enviada (`YYYY-MM-DD`).
             * @example 2026-09-19
             */
            fecha: string;
            /**
             * Format: uuid
             * @description Id del turno reservado.
             * @example 3f1c2a9e-5b7d-4e8a-9c21-6d4b0f8e1a73
             */
            turnoId: string;
            /**
             * Format: uuid
             * @description Id de la zona reservada.
             * @example b8e4d7c2-1a6f-4c3b-8e95-2f7a0d6c4b19
             */
            zonaId: string;
            /**
             * @description Cantidad de comensales reservados.
             * @example 4
             */
            comensales: number;
        };
        /** @description Cuerpo del `409` de la creación de reservas. */
        ReservaRechazadaRespuesta: {
            /**
             * @description Siempre 409.
             * @example 409
             */
            statusCode: number;
            /**
             * @description Explicación general en español.
             * @example No se pudo crear la reserva
             */
            message: string;
            /**
             * @description Nombre estándar del código HTTP.
             * @example Conflict
             */
            error: string;
            /** @description Todas las reglas que impiden la reserva, en el orden fijo de `CodigoMotivo`. Vacío solo cuando el rechazo se debe a un choque con reservas simultáneas. */
            motivos: components["schemas"]["MotivoNoDisponible"][];
        };
        ConsultarReservaDto: {
            /**
             * @description Código alfanumérico de 8 caracteres. Se compara sin distinguir mayúsculas y minúsculas.
             * @example K7PM3QXA
             */
            codigo: string;
            /**
             * Format: email
             * @description Email con el que se hizo la reserva. Se compara sin distinguir mayúsculas y minúsculas.
             * @example ana.perez@example.com
             */
            email: string;
        };
        CancelarReservaDto: {
            /**
             * Format: email
             * @description Email registrado en la reserva.
             * @example ana.perez@example.com
             */
            email: string;
        };
        TurnoReservaRespuesta: {
            /**
             * Format: uuid
             * @description Id del turno.
             * @example 3f1c2a9e-5b7d-4e8a-9c21-6d4b0f8e1a73
             */
            id: string;
            /**
             * @description Hora local de inicio (`HH:mm`), sin conversión de zona horaria.
             * @example 20:00
             */
            horaInicio: string;
            /**
             * @description Hora local de fin (`HH:mm`). Si es anterior a la de inicio, el turno termina al día siguiente.
             * @example 23:30
             */
            horaFin: string;
        };
        ZonaReservaRespuesta: {
            /**
             * Format: uuid
             * @description Id de la zona.
             * @example b8e4d7c2-1a6f-4c3b-8e95-2f7a0d6c4b19
             */
            id: string;
            /**
             * @description Nombre de la zona.
             * @example STANDARD
             * @enum {string}
             */
            nombre: "STANDARD" | "VIP";
        };
        ReservaConsultadaRespuesta: {
            /**
             * @description Código alfanumérico de 8 caracteres.
             * @example K7PM3QXA
             */
            codigoReserva: string;
            /**
             * @description Estado actual de la reserva.
             * @example CONFIRMADA
             * @enum {string}
             */
            estado: "PENDIENTE" | "CONFIRMADA" | "CANCELADA" | "NO_SHOW";
            /**
             * Format: date
             * @description Fecha de calendario local del restaurante (`YYYY-MM-DD`).
             * @example 2026-09-19
             */
            fecha: string;
            /**
             * @description Cantidad de comensales reservados.
             * @example 4
             */
            comensales: number;
            turno: components["schemas"]["TurnoReservaRespuesta"];
            zona: components["schemas"]["ZonaReservaRespuesta"];
        };
        MesaReservaRespuesta: {
            /**
             * Format: uuid
             * @description Id de la mesa.
             * @example e1a7c3f5-2d94-4b60-8a1e-9f3c6b0d7a52
             */
            id: string;
            /**
             * @description Etiqueta de la mesa en el salón.
             * @example V2
             */
            etiqueta: string;
        };
        ReservaAdminRespuesta: {
            /**
             * Format: uuid
             * @description Identificador interno de la reserva, el que usan las demás rutas de admin.
             * @example 9c4e1d70-3a2b-4c58-b1f6-7e0a5d2c8b34
             */
            id: string;
            /**
             * @description Código alfanumérico de 8 caracteres.
             * @example R2WN8HDE
             */
            codigoReserva: string;
            /**
             * @description Estado actual de la reserva.
             * @example PENDIENTE
             * @enum {string}
             */
            estado: "PENDIENTE" | "CONFIRMADA" | "CANCELADA" | "NO_SHOW";
            /**
             * Format: date
             * @description Fecha de calendario local del restaurante (`YYYY-MM-DD`).
             * @example 2026-09-19
             */
            fecha: string;
            /**
             * @description Cantidad de comensales reservados.
             * @example 6
             */
            comensales: number;
            /**
             * @description Nombre de quien reservó.
             * @example Ana Pérez
             */
            nombreCliente: string;
            /**
             * Format: email
             * @description Email de quien reservó, tal cual se guardó.
             * @example ana.perez@example.com
             */
            emailCliente: string;
            /**
             * @description Teléfono de contacto, en formato libre.
             * @example +54 9 11 5555-1234
             */
            telefonoCliente: string;
            turno: components["schemas"]["TurnoReservaRespuesta"];
            zona: components["schemas"]["ZonaReservaRespuesta"];
            mesa: components["schemas"]["MesaReservaRespuesta"];
            /**
             * Format: date-time
             * @description Instante de creación de la reserva, en UTC.
             * @example 2026-09-17T14:32:10.000Z
             */
            createdAt: string;
        };
        ListadoReservasRespuesta: {
            /** @description Reservas de la página, en orden cronológico. */
            items: components["schemas"]["ReservaAdminRespuesta"][];
            /**
             * @description Cantidad total de reservas que cumplen los filtros, sin paginar.
             * @example 1
             */
            total: number;
            /**
             * @description Tamaño de página aplicado.
             * @example 20
             */
            limit: number;
            /**
             * @description Desplazamiento aplicado.
             * @example 0
             */
            offset: number;
        };
        /** @description Forma pública de una Zona: sin `aforoMaximo` ni Mesas, datos operativos del salón sin uso para quien todavía no reservó. */
        ZonaPublicaRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /**
             * @example VIP
             * @enum {string}
             */
            nombre: "STANDARD" | "VIP";
            /** @example 2 */
            minComensales: number;
            /** @example 12 */
            maxComensales: number;
            /** @example 24 */
            anticipacionMinHoras: number;
            /** @example 60 */
            anticipacionMaxDias: number;
            /** @example 24 */
            ventanaCancelacionHoras: number;
            /** @example true */
            requiereConfirmacionAdmin: boolean;
        };
        /** @description Forma pública de un Turno activo: sin el campo `activo` (todos los devueltos ya lo son). `horaInicio`/`horaFin` viajan en el mismo formato que ya usa `TurnoRespuestaDto` de `GET /admin/turnos`. */
        TurnoPublicoRespuestaDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /**
             * @example SABADO
             * @enum {string}
             */
            diaSemana: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            /** @example 1970-01-01T20:00:00.000Z */
            horaInicio: string;
            /** @example 1970-01-01T23:30:00.000Z */
            horaFin: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_estado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El backend está operativo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    DisponibilidadController_consultar: {
        parameters: {
            query: {
                /** @description Fecha de calendario local del restaurante, sin hora (`YYYY-MM-DD`). Un instante con hora (por ejemplo `2026-09-15T12:00:00Z`) o una fecha inexistente se rechazan con `400`. */
                fecha: string;
                /** @description Id del turno a consultar. */
                turnoId: string;
                /** @description Id de la zona a consultar. */
                zonaId: string;
                /** @description Cantidad de comensales de la reserva que se quiere hacer. Entero, mínimo 1. */
                comensales: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La consulta es válida. Informa si hay lugar, cuántos comensales entran todavía y, si no hay lugar, todos los motivos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadRespuesta"];
                };
            };
            /** @description La consulta está mal formada: falta un parámetro, la fecha no es `YYYY-MM-DD` o no existe, un id no es UUID, o `comensales` no es un entero mayor o igual a 1. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description El turno o la zona indicados no existen. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    ZonasPublicasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Zonas. Una lista vacía responde `200`, no `404`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonaPublicaRespuestaDto"][];
                };
            };
        };
    };
    TurnosPublicosController_listar: {
        parameters: {
            query?: {
                /** @description Filtra los Turnos activos devueltos por día de la semana. */
                diaSemana?: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Turnos activos, opcionalmente filtrado por día de la semana. Una lista vacía responde `200`, no `404`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoPublicoRespuestaDto"][];
                };
            };
            /** @description `diaSemana` no es uno de los siete días válidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    ReservasController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearReservaDto"];
            };
        };
        responses: {
            /** @description Reserva creada. Devuelve el código que el cliente usa para consultarla o cancelarla. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaCreadaRespuesta"];
                };
            };
            /** @description El body está mal formado: falta un campo, la fecha no es `YYYY-MM-DD` o no existe, un id no es UUID, `comensales` no es un entero mayor o igual a 1, el email no es válido o el nombre o el teléfono están vacíos o son demasiado largos, o el body trae un campo que no es de los siete (por ejemplo `mesaId` o `estado`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description El turno o la zona indicados no existen. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No se pudo crear la reserva. Si alguna regla de negocio lo impide, `motivos` trae todas las que fallan, en el mismo orden y con los mismos códigos que la consulta de disponibilidad. Si el problema fue un choque con otras reservas hechas al mismo tiempo, `motivos` puede venir vacío y conviene reintentar. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaRechazadaRespuesta"];
                };
            };
        };
    };
    ReservasController_consultar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultarReservaDto"];
            };
        };
        responses: {
            /** @description El código y el email corresponden a una misma reserva, en cualquier estado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaConsultadaRespuesta"];
                };
            };
            /** @description El body está mal formado: falta `codigo` o `email`, el código no es alfanumérico de 8 caracteres, el email no es válido o hay campos no declarados. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No existe una reserva con ese código y email. Es la misma respuesta si el código no existe y si el email no coincide, sin indicar cuál dato falló. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Se superó el límite de consultas permitidas en la ventana configurada. Se rechaza antes de validar el body y de buscar la reserva. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReservasController_cancelar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Código alfanumérico de 8 caracteres. Se compara sin distinguir mayúsculas y minúsculas. */
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelarReservaDto"];
            };
        };
        responses: {
            /** @description Reserva cancelada; respuesta sin cuerpo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El código no es alfanumérico de 8 caracteres o el body no trae un email válido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description No existe una reserva con ese código y email. Es la misma respuesta si el código no existe y si el email no coincide, sin indicar cuál dato falló. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La reserva ya está en un estado terminal (CANCELADA o NO_SHOW), o al inicio de su turno le quedan menos horas que la ventana mínima de cancelación de su zona. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Se superó el límite de intentos de cancelación permitidos en la ventana configurada. Se rechaza antes de validar código y email. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login exitoso: devuelve el JWT de acceso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Credenciales inválidas: email inexistente o contraseña incorrecta. El mensaje es genérico y no distingue cuál dato falló. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Se superó el límite de intentos de login permitidos en la ventana configurada (rate limiting). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ZonasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Zonas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonaRespuestaDto"][];
                };
            };
        };
    };
    ZonasController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarZonaDto"];
            };
        };
        responses: {
            /** @description La zona se actualizó. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonaRespuestaDto"];
                };
            };
            /** @description La zona indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No se pudo actualizar la zona por una edición concurrente (conflicto de serialización agotando los reintentos). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MesasController_listar: {
        parameters: {
            query?: {
                /** @description Filtra las Mesas devueltas por Zona. */
                zonaId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Mesas, opcionalmente filtrado por Zona. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MesaRespuestaDto"][];
                };
            };
        };
    };
    MesasController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearMesaDto"];
            };
        };
        responses: {
            /** @description La mesa se creó. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MesaRespuestaDto"];
                };
            };
            /** @description La zona indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe una mesa con esa etiqueta. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MesasController_eliminar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La mesa se eliminó, sin cuerpo en la respuesta. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La mesa indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La mesa tiene reservas asociadas de cualquier estado (PENDIENTE, CONFIRMADA, CANCELADA o NO_SHOW): no se puede eliminar. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MesasController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarMesaDto"];
            };
        };
        responses: {
            /** @description La mesa se actualizó. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MesaRespuestaDto"];
                };
            };
            /** @description La mesa o la zona indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La mesa tiene una reserva activa con más comensales que la nueva capacidad, reservas activas que impiden cambiarla de zona, ya existe otra mesa con la etiqueta indicada, o no se pudo actualizar por una edición concurrente (conflicto de serialización agotando los reintentos). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HorariosController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Turnos, incluidos los inactivos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoRespuestaDto"][];
                };
            };
        };
    };
    HorariosController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearTurnoDto"];
            };
        };
        responses: {
            /** @description El turno se creó. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoRespuestaDto"];
                };
            };
            /** @description Ya existe un turno para ese día y esa hora de inicio. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HorariosController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarTurnoDto"];
            };
        };
        responses: {
            /** @description El turno se actualizó. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoRespuestaDto"];
                };
            };
            /** @description El turno indicado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe un turno para ese día y esa hora de inicio. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReservasController_listar: {
        parameters: {
            query?: {
                /** @description Fecha de calendario local del restaurante, sin hora (`YYYY-MM-DD`). */
                fecha?: string;
                /** @description Estado de la reserva. */
                estado?: "PENDIENTE" | "CONFIRMADA" | "CANCELADA" | "NO_SHOW";
                /** @description Id de la zona. Un id inexistente devuelve una lista vacía. */
                zonaId?: string;
                /** @description Id del turno. Un id inexistente devuelve una lista vacía. */
                turnoId?: string;
                /** @description Cantidad máxima de reservas por página. */
                limit?: number;
                /** @description Cantidad de reservas a saltear desde el inicio del listado. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de reservas. Si ninguna cumple los filtros, `items` viene vacío y `total` es 0. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListadoReservasRespuesta"];
                };
            };
            /** @description Un filtro está mal formado: la fecha no es `YYYY-MM-DD` o no existe, el estado no es uno de los cuatro, un id no es UUID, `limit` u `offset` están fuera de rango, o hay parámetros no declarados. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token ausente, inválido o expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token válido sin rol `ADMIN`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Se superó el límite de solicitudes al listado en la ventana configurada. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReservasController_marcarNoShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserva marcada NO_SHOW; respuesta sin cuerpo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El identificador de la reserva no es un UUID válido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token ausente, inválido o expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token válido sin rol ADMIN. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La reserva indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La reserva no está CONFIRMADA, o su turno todavía no terminó. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    ReservasController_confirmar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserva confirmada; respuesta sin cuerpo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El identificador de la reserva no es un UUID válido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token ausente, inválido o expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token válido sin rol ADMIN. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La reserva indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La reserva no está PENDIENTE. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
    ReservasController_rechazar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserva rechazada; respuesta sin cuerpo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El identificador de la reserva no es un UUID válido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token ausente, inválido o expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description Token válido sin rol ADMIN. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La reserva indicada no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
            /** @description La reserva no está PENDIENTE. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorRespuesta"];
                };
            };
        };
    };
}
